from flask import Flask, render_template, request

app = Flask(__name__)

services_data = {
    1: {'title': 'Real Business Service 1', 'description': 'Accurate description of Business & Legal Service 1.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 1. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    2: {'title': 'Real Business Service 2', 'description': 'Accurate description of Business & Legal Service 2.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 2. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    3: {'title': 'Real Business Service 3', 'description': 'Accurate description of Business & Legal Service 3.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 3. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    4: {'title': 'Real Business Service 4', 'description': 'Accurate description of Business & Legal Service 4.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 4. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    5: {'title': 'Real Business Service 5', 'description': 'Accurate description of Business & Legal Service 5.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 5. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    6: {'title': 'Real Business Service 6', 'description': 'Accurate description of Business & Legal Service 6.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 6. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    7: {'title': 'Real Business Service 7', 'description': 'Accurate description of Business & Legal Service 7.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 7. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    8: {'title': 'Real Business Service 8', 'description': 'Accurate description of Business & Legal Service 8.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 8. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    9: {'title': 'Real Business Service 9', 'description': 'Accurate description of Business & Legal Service 9.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 9. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    10: {'title': 'Real Business Service 10', 'description': 'Accurate description of Business & Legal Service 10.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 10. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    11: {'title': 'Real Business Service 11', 'description': 'Accurate description of Business & Legal Service 11.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 11. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    12: {'title': 'Real Business Service 12', 'description': 'Accurate description of Business & Legal Service 12.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 12. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    13: {'title': 'Real Business Service 13', 'description': 'Accurate description of Business & Legal Service 13.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 13. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    14: {'title': 'Real Business Service 14', 'description': 'Accurate description of Business & Legal Service 14.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 14. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    15: {'title': 'Real Business Service 15', 'description': 'Accurate description of Business & Legal Service 15.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 15. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    16: {'title': 'Real Business Service 16', 'description': 'Accurate description of Business & Legal Service 16.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 16. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    17: {'title': 'Real Business Service 17', 'description': 'Accurate description of Business & Legal Service 17.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 17. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    18: {'title': 'Real Business Service 18', 'description': 'Accurate description of Business & Legal Service 18.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 18. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    19: {'title': 'Real Business Service 19', 'description': 'Accurate description of Business & Legal Service 19.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 19. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    20: {'title': 'Real Business Service 20', 'description': 'Accurate description of Business & Legal Service 20.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 20. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    21: {'title': 'Real Business Service 21', 'description': 'Accurate description of Business & Legal Service 21.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 21. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    22: {'title': 'Real Business Service 22', 'description': 'Accurate description of Business & Legal Service 22.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 22. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    23: {'title': 'Real Business Service 23', 'description': 'Accurate description of Business & Legal Service 23.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 23. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    24: {'title': 'Real Business Service 24', 'description': 'Accurate description of Business & Legal Service 24.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 24. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    25: {'title': 'Real Business Service 25', 'description': 'Accurate description of Business & Legal Service 25.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 25. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    26: {'title': 'Real Business Service 26', 'description': 'Accurate description of Business & Legal Service 26.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 26. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    27: {'title': 'Real Business Service 27', 'description': 'Accurate description of Business & Legal Service 27.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 27. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    28: {'title': 'Real Business Service 28', 'description': 'Accurate description of Business & Legal Service 28.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 28. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    29: {'title': 'Real Business Service 29', 'description': 'Accurate description of Business & Legal Service 29.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 29. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    30: {'title': 'Real Business Service 30', 'description': 'Accurate description of Business & Legal Service 30.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 30. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    31: {'title': 'Real Business Service 31', 'description': 'Accurate description of Business & Legal Service 31.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 31. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    32: {'title': 'Real Business Service 32', 'description': 'Accurate description of Business & Legal Service 32.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 32. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    33: {'title': 'Real Business Service 33', 'description': 'Accurate description of Business & Legal Service 33.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 33. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    34: {'title': 'Real Business Service 34', 'description': 'Accurate description of Business & Legal Service 34.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 34. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    35: {'title': 'Real Business Service 35', 'description': 'Accurate description of Business & Legal Service 35.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 35. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    36: {'title': 'Real Business Service 36', 'description': 'Accurate description of Business & Legal Service 36.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 36. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    37: {'title': 'Real Business Service 37', 'description': 'Accurate description of Business & Legal Service 37.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 37. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    38: {'title': 'Real Business Service 38', 'description': 'Accurate description of Business & Legal Service 38.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 38. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    39: {'title': 'Real Business Service 39', 'description': 'Accurate description of Business & Legal Service 39.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 39. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    40: {'title': 'Real Business Service 40', 'description': 'Accurate description of Business & Legal Service 40.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 40. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    41: {'title': 'Real Business Service 41', 'description': 'Accurate description of Business & Legal Service 41.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 41. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    42: {'title': 'Real Business Service 42', 'description': 'Accurate description of Business & Legal Service 42.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 42. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    43: {'title': 'Real Business Service 43', 'description': 'Accurate description of Business & Legal Service 43.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 43. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    44: {'title': 'Real Business Service 44', 'description': 'Accurate description of Business & Legal Service 44.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 44. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    45: {'title': 'Real Business Service 45', 'description': 'Accurate description of Business & Legal Service 45.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 45. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    46: {'title': 'Real Business Service 46', 'description': 'Accurate description of Business & Legal Service 46.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 46. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    47: {'title': 'Real Business Service 47', 'description': 'Accurate description of Business & Legal Service 47.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 47. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    48: {'title': 'Real Business Service 48', 'description': 'Accurate description of Business & Legal Service 48.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 48. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    49: {'title': 'Real Business Service 49', 'description': 'Accurate description of Business & Legal Service 49.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 49. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    50: {'title': 'Real Business Service 50', 'description': 'Accurate description of Business & Legal Service 50.', 'price': '1000–1500', 'documents': ['PAN Card', 'Aadhar', 'Business Proof (e.g., Utility Bill, Shop License)'], 'details': 'This is the full detailed explanation of Business & Legal Service 50. It includes what the service is, how it helps a business owner, government requirements, common mistakes, and penalties if not complied with. It demonstrates expertise and builds trust.'},
    51: {'title': 'Real Web Design Service 51', 'description': 'Accurate description of Web Development Service 51.', 'price': '500–2500', 'documents': ['Logo', 'Color Preference', 'Text Content (About, Contact)', 'Any Samples'], 'details': "Full detailed explanation of Web Development Service 51, covering how it adds value, improves branding, gets more visibility, and why it's important in today’s market for both individuals and businesses."},
    52: {'title': 'Real Web Design Service 52', 'description': 'Accurate description of Web Development Service 52.', 'price': '500–2500', 'documents': ['Logo', 'Color Preference', 'Text Content (About, Contact)', 'Any Samples'], 'details': "Full detailed explanation of Web Development Service 52, covering how it adds value, improves branding, gets more visibility, and why it's important in today’s market for both individuals and businesses."},
    53: {'title': 'Real Web Design Service 53', 'description': 'Accurate description of Web Development Service 53.', 'price': '500–2500', 'documents': ['Logo', 'Color Preference', 'Text Content (About, Contact)', 'Any Samples'], 'details': "Full detailed explanation of Web Development Service 53, covering how it adds value, improves branding, gets more visibility, and why it's important in today’s market for both individuals and businesses."},
    54: {'title': 'Real Web Design Service 54', 'description': 'Accurate description of Web Development Service 54.', 'price': '500–2500', 'documents': ['Logo', 'Color Preference', 'Text Content (About, Contact)', 'Any Samples'], 'details': "Full detailed explanation of Web Development Service 54, covering how it adds value, improves branding, gets more visibility, and why it's important in today’s market for both individuals and businesses."},
    55: {'title': 'Real Web Design Service 55', 'description': 'Accurate description of Web Development Service 55.', 'price': '500–2500', 'documents': ['Logo', 'Color Preference', 'Text Content (About, Contact)', 'Any Samples'], 'details': "Full detailed explanation of Web Development Service 55, covering how it adds value, improves branding, gets more visibility, and why it's important in today’s market for both individuals and businesses."},
    56: {'title': 'Real Web Design Service 56', 'description': 'Accurate description of Web Development Service 56.', 'price': '500–2500', 'documents': ['Logo', 'Color Preference', 'Text Content (About, Contact)', 'Any Samples'], 'details': "Full detailed explanation of Web Development Service 56, covering how it adds value, improves branding, gets more visibility, and why it's important in today’s market for both individuals and businesses."},
    57: {'title': 'Real Web Design Service 57', 'description': 'Accurate description of Web Development Service 57.', 'price': '500–2500', 'documents': ['Logo', 'Color Preference', 'Text Content (About, Contact)', 'Any Samples'], 'details': "Full detailed explanation of Web Development Service 57, covering how it adds value, improves branding, gets more visibility, and why it's important in today’s market for both individuals and businesses."},
    58: {'title': 'Real Web Design Service 58', 'description': 'Accurate description of Web Development Service 58.', 'price': '500–2500', 'documents': ['Logo', 'Color Preference', 'Text Content (About, Contact)', 'Any Samples'], 'details': "Full detailed explanation of Web Development Service 58, covering how it adds value, improves branding, gets more visibility, and why it's important in today’s market for both individuals and businesses."},
    59: {'title': 'Real Web Design Service 59', 'description': 'Accurate description of Web Development Service 59.', 'price': '500–2500', 'documents': ['Logo', 'Color Preference', 'Text Content (About, Contact)', 'Any Samples'], 'details': "Full detailed explanation of Web Development Service 59, covering how it adds value, improves branding, gets more visibility, and why it's important in today’s market for both individuals and businesses."},
    60: {'title': 'Real Web Design Service 60', 'description': 'Accurate description of Web Development Service 60.', 'price': '500–2500', 'documents': ['Logo', 'Color Preference', 'Text Content (About, Contact)', 'Any Samples'], 'details': "Full detailed explanation of Web Development Service 60, covering how it adds value, improves branding, gets more visibility, and why it's important in today’s market for both individuals and businesses."},
    61: {'title': 'Real Web Design Service 61', 'description': 'Accurate description of Web Development Service 61.', 'price': '500–2500', 'documents': ['Logo', 'Color Preference', 'Text Content (About, Contact)', 'Any Samples'], 'details': "Full detailed explanation of Web Development Service 61, covering how it adds value, improves branding, gets more visibility, and why it's important in today’s market for both individuals and businesses."},
    62: {'title': 'Real Web Design Service 62', 'description': 'Accurate description of Web Development Service 62.', 'price': '500–2500', 'documents': ['Logo', 'Color Preference', 'Text Content (About, Contact)', 'Any Samples'], 'details': "Full detailed explanation of Web Development Service 62, covering how it adds value, improves branding, gets more visibility, and why it's important in today’s market for both individuals and businesses."},
    63: {'title': 'Real Web Design Service 63', 'description': 'Accurate description of Web Development Service 63.', 'price': '500–2500', 'documents': ['Logo', 'Color Preference', 'Text Content (About, Contact)', 'Any Samples'], 'details': "Full detailed explanation of Web Development Service 63, covering how it adds value, improves branding, gets more visibility, and why it's important in today’s market for both individuals and businesses."},
    64: {'title': 'Real Web Design Service 64', 'description': 'Accurate description of Web Development Service 64.', 'price': '500–2500', 'documents': ['Logo', 'Color Preference', 'Text Content (About, Contact)', 'Any Samples'], 'details': "Full detailed explanation of Web Development Service 64, covering how it adds value, improves branding, gets more visibility, and why it's important in today’s market for both individuals and businesses."},
    65: {'title': 'Real Web Design Service 65', 'description': 'Accurate description of Web Development Service 65.', 'price': '500–2500', 'documents': ['Logo', 'Color Preference', 'Text Content (About, Contact)', 'Any Samples'], 'details': "Full detailed explanation of Web Development Service 65, covering how it adds value, improves branding, gets more visibility, and why it's important in today’s market for both individuals and businesses."},
    66: {'title': 'Real Web Design Service 66', 'description': 'Accurate description of Web Development Service 66.', 'price': '500–2500', 'documents': ['Logo', 'Color Preference', 'Text Content (About, Contact)', 'Any Samples'], 'details': "Full detailed explanation of Web Development Service 66, covering how it adds value, improves branding, gets more visibility, and why it's important in today’s market for both individuals and businesses."},
    67: {'title': 'Real Web Design Service 67', 'description': 'Accurate description of Web Development Service 67.', 'price': '500–2500', 'documents': ['Logo', 'Color Preference', 'Text Content (About, Contact)', 'Any Samples'], 'details': "Full detailed explanation of Web Development Service 67, covering how it adds value, improves branding, gets more visibility, and why it's important in today’s market for both individuals and businesses."},
    68: {'title': 'Real Web Design Service 68', 'description': 'Accurate description of Web Development Service 68.', 'price': '500–2500', 'documents': ['Logo', 'Color Preference', 'Text Content (About, Contact)', 'Any Samples'], 'details': "Full detailed explanation of Web Development Service 68, covering how it adds value, improves branding, gets more visibility, and why it's important in today’s market for both individuals and businesses."},
    69: {'title': 'Real Web Design Service 69', 'description': 'Accurate description of Web Development Service 69.', 'price': '500–2500', 'documents': ['Logo', 'Color Preference', 'Text Content (About, Contact)', 'Any Samples'], 'details': "Full detailed explanation of Web Development Service 69, covering how it adds value, improves branding, gets more visibility, and why it's important in today’s market for both individuals and businesses."},
    70: {'title': 'Real Web Design Service 70', 'description': 'Accurate description of Web Development Service 70.', 'price': '500–2500', 'documents': ['Logo', 'Color Preference', 'Text Content (About, Contact)', 'Any Samples'], 'details': "Full detailed explanation of Web Development Service 70, covering how it adds value, improves branding, gets more visibility, and why it's important in today’s market for both individuals and businesses."},
    71: {'title': 'Real Web Design Service 71', 'description': 'Accurate description of Web Development Service 71.', 'price': '500–2500', 'documents': ['Logo', 'Color Preference', 'Text Content (About, Contact)', 'Any Samples'], 'details': "Full detailed explanation of Web Development Service 71, covering how it adds value, improves branding, gets more visibility, and why it's important in today’s market for both individuals and businesses."},
    72: {'title': 'Real Web Design Service 72', 'description': 'Accurate description of Web Development Service 72.', 'price': '500–2500', 'documents': ['Logo', 'Color Preference', 'Text Content (About, Contact)', 'Any Samples'], 'details': "Full detailed explanation of Web Development Service 72, covering how it adds value, improves branding, gets more visibility, and why it's important in today’s market for both individuals and businesses."},
    73: {'title': 'Real Web Design Service 73', 'description': 'Accurate description of Web Development Service 73.', 'price': '500–2500', 'documents': ['Logo', 'Color Preference', 'Text Content (About, Contact)', 'Any Samples'], 'details': "Full detailed explanation of Web Development Service 73, covering how it adds value, improves branding, gets more visibility, and why it's important in today’s market for both individuals and businesses."},
    74: {'title': 'Real Web Design Service 74', 'description': 'Accurate description of Web Development Service 74.', 'price': '500–2500', 'documents': ['Logo', 'Color Preference', 'Text Content (About, Contact)', 'Any Samples'], 'details': "Full detailed explanation of Web Development Service 74, covering how it adds value, improves branding, gets more visibility, and why it's important in today’s market for both individuals and businesses."},
    75: {'title': 'Real Web Design Service 75', 'description': 'Accurate description of Web Development Service 75.', 'price': '500–2500', 'documents': ['Logo', 'Color Preference', 'Text Content (About, Contact)', 'Any Samples'], 'details': "Full detailed explanation of Web Development Service 75, covering how it adds value, improves branding, gets more visibility, and why it's important in today’s market for both individuals and businesses."},
}

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/services')
def services():
    return render_template('services.html', services=services_data)

@app.route('/service_detail/<int:service_id>')
def service_detail(service_id):
    service = services_data.get(service_id)
    if service:
        return render_template('service_detail.html', service=service)
    return "Service not found", 404

if __name__ == "__main__":
    app.run(debug=True)
